# trigger:
#   branches:
#     include:
#       - main  # Trigger on push to main branch

pool:
  name: 'Azure Pipelines'  # Use the default Azure-hosted agent pool
  vmImage: 'ubuntu-latest'  # Specify the hosted Ubuntu image

variables:
  MY_DOCKER_IMAGE: 'simple-web-app'  # My app name

stages:
- stage: Build
  jobs:
  - job: BuildingDockerFileAndPushToPipelineWorkSpace
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        dockerfile: '**/dockerfile'
        repository: $(MY_DOCKER_IMAGE)
        tags: web_app

    - script: |
        docker save -o $(Pipeline.Workspace)/webapp.tar $(MY_DOCKER_IMAGE):web_app
      displayName: 'Save Docker image to tar'

- stage: Deploy
  jobs:
  - job: DeployToEC2
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'MyEC2SSHConnection'  # SSH service connection to your EC2 instance
        runOptions: 'inline'
        inline: |
          # Load the Docker image
          docker load -i $(Pipeline.Workspace)/webapp.tar

          # Stop and remove any existing container with the same name
          docker stop my-web-app || true
          docker rm my-web-app || true

          # Run the new container
          docker run -d -p 80:80 --name my-web-app $(MY_DOCKER_IMAGE):web_app
        continueOnError: true
